import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    // Apply to all JavaScript files
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        indexedDB: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        fetch: 'readonly',
        AbortController: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        structuredClone: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        DragEvent: 'readonly',
        ClipboardEvent: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        crypto: 'readonly',

        // External libraries loaded via CDN
        bootstrap: 'readonly',
        Sortable: 'readonly',
        Quill: 'readonly',
        jspdf: 'readonly',
        jsPDF: 'readonly',
        html2canvas: 'readonly',
        docx: 'readonly',

        // App globals (defined in site.js or data files)
        DM_TOOLBOX_BUILD: 'readonly',
        LevelUpData: 'readonly',
        SPELLS_DATA: 'readonly',
        RULES_DATA: 'readonly',

        // Cross-file globals (loaded via HTML script tags)
        IndexedDBStorage: 'readonly',
        CharacterCreationWizard: 'readonly',
        LevelUpSystem: 'readonly',
        JournalExport: 'readonly',
        showToast: 'readonly',
        showUserError: 'readonly',

        // DOM API constants
        Node: 'readonly',
      },
    },
    rules: {
      // ===== Error Prevention =====
      // Note: Many "unused" vars are intentionally exposed via window.* pattern
      // Set to warn so existing code doesn't block commits
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none'
      }],
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unreachable': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],

      // ===== Best Practices =====
      'no-var': 'error',
      'prefer-const': ['warn', { destructuring: 'all' }],  // Warn for now, many existing issues
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-implicit-globals': 'error',

      // ===== Relaxed Rules (match existing code) =====
      'no-prototype-builtins': 'off',
      'no-case-declarations': 'off',
      'no-useless-escape': 'off',
      'no-async-promise-executor': 'off',  // Used intentionally in IndexedDB code

      // ===== Stylistic (info only, not errors) =====
      'no-console': 'off',  // Console logging is allowed
    },
  },
  {
    // Specific rules for pure modules (stricter)
    files: ['js/modules/**/*.js'],
    rules: {
      'no-restricted-globals': ['error', {
        name: 'document',
        message: 'Modules should not access DOM directly. Use dependency injection.'
      }, {
        name: 'window',
        message: 'Modules should not access window directly. Use dependency injection.'
      }],
    },
  },
  {
    // Loot Generator (data/engine/ui split) — cross-file globals shared via <script src>
    files: ['js/loot/**/*.js'],
    languageOptions: {
      globals: {
        $: 'writable',
        ADJS: 'writable',
        ADV_GEAR_ITEMS: 'writable',
        ANIMALS: 'writable',
        BAG_ITEMS: 'writable',
        CATS: 'writable',
        CLOTHING_ITEMS: 'writable',
        COIN_ITEMS: 'writable',
        COLORS: 'writable',
        COND: 'writable',
        FOOD_ITEMS: 'writable',
        GEM_ITEMS: 'writable',
        MARKS: 'writable',
        MATERIALS: 'writable',
        MONSTER_TEMPLATES: 'writable',
        MUNDANE_ITEMS: 'writable',
        PATTERNS: 'writable',
        POTION_ITEMS: 'writable',
        PRESETS: 'writable',
        QUICK_BUNDLES: 'writable',
        SCENTS: 'writable',
        SCROLL_ITEMS: 'writable',
        SIMPLE_ICONS: 'writable',
        SIZES: 'writable',
        TEMPLATE: 'writable',
        TOOLKIT_ITEMS: 'writable',
        TOOL_ITEMS: 'writable',
        WEAPON_ARMOR_ITEMS: 'writable',
        clamp: 'writable',
        coinBundle: 'writable',
        formatCoinBundle: 'writable',
        generateCount: 'writable',
        generateToBudget: 'writable',
        gpToSp: 'writable',
        makeOne: 'writable',
        pick: 'writable',
        prand: 'writable',
        spToGp: 'writable',
        tags: 'writable',
        toTitle: 'writable',
      },
    },
  },
  {
    // Name Generator (data/engine/ui split) — cross-file globals shared via <script src>
    files: ['js/name/**/*.js'],
    languageOptions: {
      globals: {
        CURRENT_CFG: 'writable',
        CURRENT_SEED: 'writable',
        HARSH_CLUSTERS: 'writable',
        RACE_PRESETS: 'writable',
        TABLES: 'writable',
        makeFullName: 'writable',
        prand: 'writable',
      },
    },
  },
  {
    // Shop Generator (data/engine/ui split) — cross-file globals shared via <script src>
    files: ['js/shop/**/*.js'],
    languageOptions: {
      globals: {
        DEFAULT_SHOP_TYPES: 'writable',
        FLAV_ADJ: 'writable',
        FLAV_DEC: 'writable',
        FLAV_MAT: 'writable',
        FLAV_UNIQUE: 'writable',
        PRESETS: 'writable',
        RESTOCK_BASE: 'writable',
        SETTLEMENT: 'writable',
        SHOPKEEPER_NAMES: 'writable',
        SHOPKEEPER_PERSONALITY: 'writable',
        SHOPKEEPER_RP: 'writable',
        SHOPS: 'writable',
        SHOP_BUYS: 'writable',
        choiceByRarity: 'writable',
        clearShopSold: 'writable',
        decorateDesc: 'writable',
        formatPrice: 'writable',
        getRestockLabel: 'writable',
        getSoldSet: 'writable',
        itemSoldKey: 'writable',
        makeShopkeeper: 'writable',
        markSold: 'writable',
        markUnsold: 'writable',
        pick: 'writable',
        prand: 'writable',
        showNegotiateModal: 'writable',
        showSellToShopModal: 'writable',
        slugifyShop: 'writable',
        uniqueLine: 'writable',
        within: 'writable',
      },
    },
  },
  {
    // Tavern Generator (data/engine/ui split) — cross-file globals shared via <script src>
    files: ['js/tavern/**/*.js'],
    languageOptions: {
      globals: {
        $: 'writable',
        AGE: 'writable',
        AMBIENCE: 'writable',
        AMBIENCE_BY_TYPE: 'writable',
        ATTIRE: 'writable',
        BARTENDER_RUMORS: 'writable',
        BARTENDER_RUMORS_BY_QUALITY: 'writable',
        BARTENDER_RUMORS_BY_SETTLEMENT: 'writable',
        BARTENDER_RUMORS_BY_TIME: 'writable',
        BARTENDER_RUMORS_BY_TYPE: 'writable',
        BUILD: 'writable',
        CULTURAL_MENU: 'writable',
        DEMEANOR: 'writable',
        DRINKS: 'writable',
        EVENTS_BY_QUALITY: 'writable',
        EVENTS_BY_SETTLEMENT: 'writable',
        EVENTS_BY_SIZE: 'writable',
        EVENTS_BY_TIME: 'writable',
        EVENTS_BY_TYPE: 'writable',
        EYES: 'writable',
        HAIR_COLOR: 'writable',
        HAIR_STYLE: 'writable',
        HOUSE_SPECIAL_DRINK: 'writable',
        HOUSE_TWISTS: 'writable',
        MANNER: 'writable',
        MEAL_BASE: 'writable',
        PATRON_HOOKS: 'writable',
        PATRON_HOOKS_BY_CONTEXT: 'writable',
        PATRON_QUIRKS: 'writable',
        PATRON_QUIRKS_BY_CONTEXT: 'writable',
        PATRON_RUMORS: 'writable',
        PATRON_RUMORS_BY_QUALITY: 'writable',
        PATRON_RUMORS_BY_SETTLEMENT: 'writable',
        PATRON_RUMORS_BY_SIZE: 'writable',
        PATRON_RUMORS_BY_TIME: 'writable',
        PATRON_RUMORS_BY_TYPE: 'writable',
        PATRON_TYPES: 'writable',
        PATRON_TYPES_BY_QUALITY: 'writable',
        PATRON_TYPES_BY_SETTLEMENT: 'writable',
        PATRON_TYPES_BY_SIZE: 'writable',
        PATRON_TYPES_BY_TIME: 'writable',
        PATRON_TYPES_BY_TYPE: 'writable',
        QUALITY: 'writable',
        SETTLEMENT: 'writable',
        SIGN_ANIMALS: 'writable',
        SIGN_COLORS: 'writable',
        SIGN_NUMS: 'writable',
        SIGN_OBJECTS: 'writable',
        SIGN_TITLES: 'writable',
        SIGN_TRAITS: 'writable',
        STAFF_BY_TYPE: 'writable',
        STAFF_ROLES: 'writable',
        TAVERN_EVENTS: 'writable',
        VOICE_ACCENT: 'writable',
        VOICE_PITCH: 'writable',
        VOICE_TIMBRE: 'writable',
        buildAmbience: 'writable',
        buildBartenderRumors: 'writable',
        buildDrinks: 'writable',
        buildEventsOnly: 'writable',
        buildInnName: 'writable',
        buildMeals: 'writable',
        buildPatronRumors: 'writable',
        buildPatrons: 'writable',
        buildRooms: 'writable',
        buildStaff: 'writable',
        clamp: 'writable',
        generateFullNPCFromStaff: 'writable',
        hashString: 'writable',
        mulberry32: 'writable',
        pick: 'writable',
        prandSection: 'writable',
        priceScale: 'writable',
      },
    },
  },
  {
    // Content-pack runtime glue modules intentionally interact with DOM globals
    files: [
      'js/modules/content-pack-manager.js',
      'js/modules/content-pack-runtime.js',
      'js/modules/content-pack-ui.js',
      'js/modules/srd-content-filter.js',
    ],
    rules: {
      'no-restricted-globals': 'off',
    },
  },
  {
    // Ignore patterns
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      '*.min.js',
      'tests/**',  // Tests have their own config via Vitest
    ],
  },
];
